/**
 * Reusable hybrid RAG.
 *
 * Public API (namespace-scoped, feature-agnostic):
 *   - indexDocument(namespace, documentId, text, metadata?) — chunk + embed + store
 *   - retrieve(namespace, query, options?)                  — hybrid (vector + keyword) search
 *   - deleteDocument(namespace, documentId)
 *   - deleteNamespace(namespace)
 *
 * Hybrid strategy: run vector search and BM25 keyword search independently, then
 * fuse their rankings with Reciprocal Rank Fusion (RRF). If embeddings or vector
 * search are unavailable (no API key, not yet indexed, provider error), it
 * degrades to keyword-only — so callers never lose functionality or pay a
 * latency cliff. Embeddings are generated by a pluggable Embedder.
 */

import { chunkText } from "@/app/lib/server/study/text";
import {
  Embedder,
  RagChunk,
  RagHit,
  RetrieveOptions,
  VectorStore,
} from "@/app/lib/server/rag/types";
import { createGeminiEmbedder, embedQuery } from "@/app/lib/server/rag/embedders/gemini";
import { createMongoVectorStore } from "@/app/lib/server/rag/stores/mongoVectorStore";
import { keywordSearch } from "@/app/lib/server/rag/keyword";

// Default wiring. Swap these to change provider/backend globally, or pass
// overrides per call for tests.
let defaultEmbedder: Embedder | null = null;
function getEmbedder(): Embedder {
  if (!defaultEmbedder) defaultEmbedder = createGeminiEmbedder();
  return defaultEmbedder;
}
const store: VectorStore = createMongoVectorStore();

// ~700-char chunks match the study repo's chunking, keeping citation/ordinal
// semantics consistent across the app.
const CHUNK_CHARS = 700;
const RRF_K = 60; // standard RRF constant.

function buildChunkId(namespace: string, documentId: string, ordinal: number) {
  return `${namespace}::${documentId}::${ordinal}`;
}

export interface IndexDocumentOptions {
  metadata?: Record<string, unknown>;
  /** Pre-computed chunks (skip internal chunking) — advanced callers only. */
  chunks?: string[];
}

/**
 * Chunk, embed, and store a document under a namespace. Replaces any existing
 * chunks for the same documentId (idempotent re-index). Throws if embedding
 * fails — callers running this in the background should catch and log.
 */
export async function indexDocument(
  namespace: string,
  documentId: string,
  text: string,
  options: IndexDocumentOptions = {},
): Promise<{ chunkCount: number }> {
  const normalized = (text || "").trim();
  if (!normalized) {
    await store.deleteDocument(namespace, documentId);
    return { chunkCount: 0 };
  }

  const pieces =
    options.chunks && options.chunks.length > 0
      ? options.chunks
      : chunkText(normalized, CHUNK_CHARS);

  const embedder = getEmbedder();
  const embeddings = await embedder.embed(pieces);

  const chunks: RagChunk[] = pieces.map((piece, ordinal) => ({
    id: buildChunkId(namespace, documentId, ordinal),
    namespace,
    documentId,
    ordinal,
    text: piece,
    embedding: embeddings[ordinal],
    metadata: options.metadata,
  }));

  await store.upsertDocument(namespace, documentId, chunks);
  return { chunkCount: chunks.length };
}

export async function deleteDocument(namespace: string, documentId: string) {
  await store.deleteDocument(namespace, documentId);
}

export async function deleteNamespace(namespace: string) {
  await store.deleteNamespace(namespace);
}

/** Reciprocal Rank Fusion: combine two ranked lists into one. */
function fuse(
  vectorHits: RagHit[],
  keywordHits: RagHit[],
  vectorWeight: number,
  keywordWeight: number,
): RagHit[] {
  const fused = new Map<string, RagHit & { _fused: number }>();

  const addRanks = (hits: RagHit[], weight: number, kind: "v" | "k") => {
    hits.forEach((hit, rank) => {
      const contribution = weight * (1 / (RRF_K + rank + 1));
      const existing = fused.get(hit.id);
      if (existing) {
        existing._fused += contribution;
        if (kind === "v") existing.vectorScore = hit.vectorScore;
        if (kind === "k") existing.keywordScore = hit.keywordScore;
      } else {
        fused.set(hit.id, { ...hit, _fused: contribution });
      }
    });
  };

  addRanks(vectorHits, vectorWeight, "v");
  addRanks(keywordHits, keywordWeight, "k");

  return Array.from(fused.values())
    .map((h) => ({ ...h, score: h._fused }))
    .sort((a, b) => b.score - a.score);
}

/**
 * Hybrid retrieval. Returns the most relevant chunks for a query, fusing vector
 * and keyword rankings. Degrades to keyword-only when vectors are unavailable.
 */
export async function retrieve(
  namespace: string,
  query: string,
  options: RetrieveOptions = {},
): Promise<RagHit[]> {
  const topK = options.topK ?? 6;
  const vectorWeight = options.vectorWeight ?? 1;
  const keywordWeight = options.keywordWeight ?? 1;
  const allowFallback = options.keywordFallback ?? true;

  // Keyword search always runs (cheap, no external dependency) and doubles as
  // the fallback. Fetch the corpus once and reuse for keyword scoring.
  const chunks = await store.listChunks(namespace);
  const keywordHits = keywordSearch(chunks, query, topK * 2);

  // Attempt vector retrieval; never let its failure break the request.
  let vectorHits: RagHit[] = [];
  if (process.env.GEMINI_API_KEY && chunks.some((c) => c.embedding?.length)) {
    try {
      const queryEmbedding = await embedQuery(query);
      vectorHits = await store.vectorSearch(namespace, queryEmbedding, topK * 2);
    } catch (error) {
      console.error("rag.retrieve.vector_failed", error);
      if (!allowFallback) throw error;
    }
  }

  if (vectorHits.length === 0) {
    // Keyword-only (either by design, not-yet-indexed, or vector failure).
    return keywordHits.slice(0, topK);
  }

  return fuse(vectorHits, keywordHits, vectorWeight, keywordWeight).slice(0, topK);
}
