/**
 * Reusable hybrid RAG.
 *
 * Public API (namespace-scoped, feature-agnostic):
 *   - indexDocument(namespace, documentId, text, metadata?) — chunk + embed + store
 *   - retrieve(namespace, query, options?)                  — hybrid (vector + keyword) search
 *   - deleteDocument(namespace, documentId)
 *   - deleteNamespace(namespace)
 *
 * Hybrid strategy: run vector search and BM25 keyword search independently, then
 * fuse their rankings with Reciprocal Rank Fusion (RRF). If embeddings or vector
 * search are unavailable (no API key, not yet indexed, provider error), it
 * degrades to keyword-only — so callers never lose functionality or pay a
 * latency cliff. Embeddings are generated by a pluggable Embedder.
 */

import { chunkText } from "@/app/lib/server/study/text";
import {
  Embedder,
  RagChunk,
  RagHit,
  RetrieveOptions,
  VectorStore,
} from "@/app/lib/server/rag/types";
import { createGeminiEmbedder, embedQuery } from "@/app/lib/server/rag/embedders/gemini";
import { createMongoVectorStore } from "@/app/lib/server/rag/stores/mongoVectorStore";
import { keywordSearch } from "@/app/lib/server/rag/keyword";

// Default wiring. Swap these to change provider/backend globally, or pass
// overrides per call for tests.
let defaultEmbedder: Embedder | null = null;
function getEmbedder(): Embedder {
  if (!defaultEmbedder) defaultEmbedder = createGeminiEmbedder();
  return defaultEmbedder;
}
const store: VectorStore = createMongoVectorStore();

// ~700-char chunks match the study repo's chunking, keeping citation/ordinal
// semantics consistent across the app.
const CHUNK_CHARS = 700;
const RRF_K = 60; // standard RRF constant.

function buildChunkId(namespace: string, documentId: string, ordinal: number) {
  return `${namespace}::${documentId}::${ordinal}`;
}

export interface IndexDocumentOptions {
  metadata?: Record<string, unknown>;
  /** Pre-computed chunks (skip internal chunking) — advanced callers only. */
  chunks?: string[];
}

/**
 * Outcome of an index attempt, so callers can persist a durable status and
 * decide whether a re-index is needed later.
 *   - "indexed"      — every chunk got an embedding (vector retrieval ready).
 *   - "keyword_only" — chunks stored without vectors (embed failed / no key);
 *                      BM25 retrieval works but vector search does not.
 *   - "empty"        — no usable text; nothing stored.
 */
export type IndexStatus = "indexed" | "keyword_only" | "empty";

export interface IndexDocumentResult {
  chunkCount: number;
  status: IndexStatus;
  /** Embedder used when vectors were produced (detect model drift on re-index). */
  embedderId?: string;
}

/**
 * Chunk, embed, and store a document under a namespace. Replaces any existing
 * chunks for the same documentId (idempotent re-index). Never throws on embed
 * failure — it stores keyword-only and reports the degraded status so the
 * caller can persist it and schedule a re-index.
 */
export async function indexDocument(
  namespace: string,
  documentId: string,
  text: string,
  options: IndexDocumentOptions = {},
): Promise<IndexDocumentResult> {
  const normalized = (text || "").trim();
  if (!normalized) {
    await store.deleteDocument(namespace, documentId);
    return { chunkCount: 0, status: "empty" };
  }

  const pieces =
    options.chunks && options.chunks.length > 0
      ? options.chunks
      : chunkText(normalized, CHUNK_CHARS);

  // Embedding failure must NOT lose the document: chunks stored without
  // vectors still power BM25 keyword retrieval (and citations). Previously a
  // failed embed threw the whole index away, leaving retrieval with nothing —
  // the tutor then answered a 100-page PDF from 3 weakly-matched chunks.
  let embeddings: number[][] = [];
  let embedderId: string | undefined;
  let embedFailed = false;
  try {
    const embedder = getEmbedder();
    embeddings = await embedder.embed(pieces);
    embedderId = embedder.id;
  } catch (error) {
    embedFailed = true;
    console.error("rag.index.embed_failed_storing_keyword_only", {
      namespace,
      documentId,
      error,
    });
  }

  const chunks: RagChunk[] = pieces.map((piece, ordinal) => ({
    id: buildChunkId(namespace, documentId, ordinal),
    namespace,
    documentId,
    ordinal,
    text: piece,
    embedding: embeddings[ordinal],
    metadata: options.metadata,
  }));

  await store.upsertDocument(namespace, documentId, chunks);
  // "indexed" only when every chunk actually carries a vector.
  const allEmbedded =
    !embedFailed &&
    chunks.length > 0 &&
    chunks.every((c) => Array.isArray(c.embedding) && c.embedding.length > 0);
  return {
    chunkCount: chunks.length,
    status: allEmbedded ? "indexed" : "keyword_only",
    embedderId: allEmbedded ? embedderId : undefined,
  };
}

export async function deleteDocument(namespace: string, documentId: string) {
  await store.deleteDocument(namespace, documentId);
}

export async function deleteNamespace(namespace: string) {
  await store.deleteNamespace(namespace);
}

/** Reciprocal Rank Fusion: combine two ranked lists into one. */
function fuse(
  vectorHits: RagHit[],
  keywordHits: RagHit[],
  vectorWeight: number,
  keywordWeight: number,
): RagHit[] {
  const fused = new Map<string, RagHit & { _fused: number }>();

  const addRanks = (hits: RagHit[], weight: number, kind: "v" | "k") => {
    hits.forEach((hit, rank) => {
      const contribution = weight * (1 / (RRF_K + rank + 1));
      const existing = fused.get(hit.id);
      if (existing) {
        existing._fused += contribution;
        if (kind === "v") existing.vectorScore = hit.vectorScore;
        if (kind === "k") existing.keywordScore = hit.keywordScore;
      } else {
        fused.set(hit.id, { ...hit, _fused: contribution });
      }
    });
  };

  addRanks(vectorHits, vectorWeight, "v");
  addRanks(keywordHits, keywordWeight, "k");

  return Array.from(fused.values())
    .map((h) => ({ ...h, score: h._fused }))
    .sort((a, b) => b.score - a.score);
}

/**
 * Expand hits with their neighboring chunks (ordinal ±n within the same
 * document). Chunks are only ~700 chars; a lone fragment often lacks the
 * sentences that make it answerable, which pushes the LLM to fill gaps from
 * prior knowledge (hallucination). Neighbors inherit a discounted score and no
 * vector/keyword scores, so relevance detection still reflects real matches.
 */
function expandWithNeighbors(
  hits: RagHit[],
  corpus: RagChunk[],
  radius: number,
): RagHit[] {
  if (radius <= 0 || hits.length === 0) return hits;
  const byDocOrdinal = new Map<string, RagChunk>();
  for (const chunk of corpus) {
    byDocOrdinal.set(`${chunk.documentId}::${chunk.ordinal}`, chunk);
  }
  const included = new Set(hits.map((h) => `${h.documentId}::${h.ordinal}`));
  const out: RagHit[] = [];
  for (const hit of hits) {
    out.push(hit);
    for (let delta = 1; delta <= radius; delta += 1) {
      for (const ordinal of [hit.ordinal - delta, hit.ordinal + delta]) {
        const key = `${hit.documentId}::${ordinal}`;
        if (included.has(key)) continue;
        const neighbor = byDocOrdinal.get(key);
        if (!neighbor) continue;
        included.add(key);
        out.push({
          id: neighbor.id,
          documentId: neighbor.documentId,
          ordinal: neighbor.ordinal,
          text: neighbor.text,
          score: hit.score * 0.5,
          metadata: neighbor.metadata,
        });
      }
    }
  }
  return out;
}

/**
 * Hybrid retrieval. Returns the most relevant chunks for a query, fusing vector
 * and keyword rankings. Degrades to keyword-only when vectors are unavailable.
 */
export async function retrieve(
  namespace: string,
  query: string,
  options: RetrieveOptions = {},
): Promise<RagHit[]> {
  const topK = options.topK ?? 6;
  const vectorWeight = options.vectorWeight ?? 1;
  const keywordWeight = options.keywordWeight ?? 1;
  const allowFallback = options.keywordFallback ?? true;
  const neighborRadius = options.expandNeighbors ?? 0;

  // Keyword search always runs (cheap, no external dependency) and doubles as
  // the fallback. Fetch the corpus once and reuse for keyword scoring.
  const chunks = await store.listChunks(namespace);
  const keywordHits = keywordSearch(chunks, query, topK * 2);

  // Attempt vector retrieval; never let its failure break the request.
  let vectorHits: RagHit[] = [];
  if (process.env.GEMINI_API_KEY && chunks.some((c) => c.embedding?.length)) {
    try {
      const queryEmbedding = await embedQuery(query);
      vectorHits = await store.vectorSearch(namespace, queryEmbedding, topK * 2);
    } catch (error) {
      console.error("rag.retrieve.vector_failed", error);
      if (!allowFallback) throw error;
    }
  }

  const fused =
    vectorHits.length === 0
      ? // Keyword-only (either by design, not-yet-indexed, or vector failure).
        keywordHits
      : fuse(vectorHits, keywordHits, vectorWeight, keywordWeight);

  // Take the strongest `topK` primary hits, expand each with its neighbors for
  // coherent windows, then re-sort by score and cap the TOTAL. Expanding after a
  // naive `slice(0, topK)` used to (a) blow past topK by up to 2*radius per hit
  // and (b) push neighbors inline so a neighbor of hit #1 could outrank a real
  // hit #8 — the returned array was no longer relevance-ordered, which the
  // caller assumes. Re-sorting + a hard budget fixes both.
  const primary = fused.slice(0, topK);
  const expanded = expandWithNeighbors(primary, chunks, neighborRadius);
  if (neighborRadius <= 0) return expanded;

  const maxTotal = topK * (1 + 2 * neighborRadius);
  return expanded
    .slice()
    .sort((a, b) => b.score - a.score)
    .slice(0, maxTotal);
}
